### ISSUE TITLE
Checksum mismatch for version 0.14.0

### ISSUE THREAD

**Issue by ezdac** [raiden-network/homebrew-raiden#10]
The raiden formular file provides a wrong sha256 checksum that mismatches the checksum of the current version provided in GitHub.

```
➜ brew install raiden
==> Installing raiden from raiden-network/raiden
==> Downloading https://github.com/raiden-network/raiden/releases/download/v0.14.0/raiden-v0.14.0-macOS.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/50646767/b8b00c80-d469-11e8-9483-32dde8956a51?X-Amz-Algorithm=AWS4-HMAC-S
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: 6b609a318e6f68d2412bee5e327764858c18023c00f1efc7db65bab539f73e79
Actual: 4cf620b29e70dd6de3bdbb4fd58e9af9ec2aeaff44abf74fc538cf867826682b
Archive: /Users/Max/Library/Caches/Homebrew/downloads/e9e43f5e83da421ea5e41b7b9512bac48281e105eee9e9c531575038efd855b8--raiden-v0.14.0-macOS.zip
To retry an incomplete download, remove the file above.
```

The sha256 digest for the file on GitHub checks out the `Actual` sha256 from brew.
```
➜ openssl dgst -sha256 ~/Downloads/raiden-v0.14.0-macOS.zip
SHA256(~/Downloads/raiden-v0.14.0-macOS.zip)= 4cf620b29e70dd6de3bdbb4fd58e9af9ec2aeaff44abf74fc538cf867826682b
```

**Comment by LefterisJP** [comment]
@ulope will take a look at this. It's the first time automatic homebrew deployment worked -- all the previous versions were manual. So something may be wrong with the automatic recipe in how the expected checksum is registered.

**Comment by ezdac** [comment]
For anyone interested, as a hotfix for the user (apart from just copying/linking the binary to `/usr/local/bin`) is to edit the expected checksum locally:

- `brew edit raiden`
- change the `sha256` to `4cf620b29e70dd6de3bdbb4fd58e9af9ec2aeaff44abf74fc538cf867826682b`
- `brew upgrade raiden`
