### ISSUE TITLE
missing quotation mark

### ISSUE THREAD

**Issue by brett-schneider** [raiden-network/homebrew-raiden#13]
in line 6 of raiden.rb there's a double qoute missing at the end

**Comment by brett-schneider** [comment]
also, the url is wrong. the correct url is
https://github.com/raiden-network/raiden/releases/download/v1.1.0/raiden-v1.1.0-macOS-x86_64.zip
whereas in raiden.rb it says (missing slash)
https://github.com/raiden-network/raiden/releases/download/v1.1.0raiden-v1.1.0macOS-x86_64.zip

**Comment by brett-schneider** [comment]
not to mention the checksum

**Comment by brett-schneider** [comment]
and the filename in the installation sub. anyway since i can't push, here's the file
[raiden.zip](https://github.com/raiden-network/homebrew-raiden/files/4807177/raiden.zip)

**Comment by ulope** [comment]
Thanks for the report @brett-schneider.
We're aware that the current build process is broken (see https://github.com/raiden-network/raiden/issues/6035)
I've fixed the formula manually. This got overlooked on the latest release. Sorry for that.
